In [1]:
import numpy as np
import random

In [10]:
np.random.random(1)      # it gives value of an array b/w 0 to 1

array([0.70363589])

In [14]:
np.random.random((3,3))    #if we required value b/w 0 to 1

array([[0.57674166, 0.16887476, 0.50680052],
       [0.25403612, 0.51678235, 0.91366647],
       [0.17728712, 0.23582264, 0.8396161 ]])

In [20]:
np.random.randint(1,4)   #if we required int valie b/w two value where end value is exclusive

2

In [22]:
np.random.randint(1,4,(4,4)) #if we required array of int value

array([[2, 1, 1, 3],
       [1, 2, 3, 2],
       [2, 2, 2, 3],
       [1, 2, 1, 3]])

In [24]:
np.random.randint(1,4,(2,4,4)) #if we required n(2) array of int value

array([[[1, 3, 1, 1],
        [1, 1, 2, 1],
        [1, 3, 2, 1],
        [2, 2, 1, 1]],

       [[2, 3, 2, 2],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 2, 1, 1]]])

In [28]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))#if we required same value in array n times for use in more array

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [33]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))     #like it we get same value same like last array

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [35]:
2**32-1    #how much value we can give of seed()

4294967295

In [37]:
np.random.rand(3)    #it also gives random value b/w 0 to 1 

array([0.13145815, 0.41366737, 0.77872881])

In [41]:
np.random.rand(3,5) # under rand(n value,n value)    #its mean gives n-no of array

array([[0.10540183, 0.28357668, 0.06556327, 0.05644419, 0.76545582],
       [0.01178803, 0.61194334, 0.33188226, 0.55964837, 0.33549965],
       [0.41118255, 0.0768555 , 0.85304299, 0.43998746, 0.12195415]])

In [43]:
np.random.randn(3,5)    #it gives neg  and pos value

array([[-0.6579709 ,  0.42211306,  0.62402334,  0.5016401 ,  0.84143473],
       [-1.64024998,  1.05800516, -0.09178444, -0.72403459, -0.40046036],
       [ 0.44532458,  0.95993965, -1.34635384,  2.01889937,  1.08237635]])

In [47]:
x=[1,2,3,4,5]      #it chice only any one value b/w given list
np.random.choice(x)

3

In [51]:
for i in range(20):  #it choice 20 times any diff value b/w given range list
    print(np.random.choice(x))

3
2
1
2
2
1
2
3
5
3
2
2
5
1
1
2
1
5
5
1


In [53]:
x

[1, 2, 3, 4, 5]

In [57]:
np.random.permutation(x)    #it promote an array value everytimes different

array([2, 1, 3, 5, 4])

In [59]:
np.random.permutation(x)    #it promote an array value everytimes different

array([5, 2, 1, 4, 3])

In [ ]:
#there are more random sampling function(we can check it on scipy.org) on webs