In [1]:
import numpy as np

*arange()

In [3]:
#np.arange(start,end,steps)
arr_1d=np.arange(1,15)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
#arange() is used to arange the value

In [5]:
even_arr=np.arange(1,15,2)
print(even_arr)

[ 1  3  5  7  9 11 13]


*linspace()

In [7]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [8]:
#use for no required b/w range

*reshape()

In [10]:
arr_2d=arr_1d.reshape(2,7)
print(arr_2d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
#it is use for convert one array into another array

*ravel()

In [13]:
#it is used to convert muldidimension array into 1d

*flatten()

In [15]:
#it is used to convert multidimension array into 1d

*transpose()

In [17]:
#it is used to convert row into coloum