In [3]:
import numpy as np

In [5]:
arr_1d=np.array([1,2,3])
print(arr_1d)


[1 2 3]


In [29]:
type(arr_1d)

numpy.ndarray

In [9]:
arr_1d.ndim

1

In [11]:
arr_2d=np.array([[1,2,4],[5,7,8]])
print(arr_2d)

[[1 2 4]
 [5 7 8]]


In [13]:
arr_2d.ndim

2

In [15]:
arr_2d.size

6

In [17]:
arr_1d.size

3

In [19]:
arr_1d.shape

(3,)

In [21]:
arr_2d.shape

(2, 3)

In [23]:
#(row,col)

In [25]:
arr_2d.dtype

dtype('int32')

In [27]:
arr_2d

array([[1, 2, 4],
       [5, 7, 8]])